// wa-webhook — WhatsApp Cloud API webhook receiver.
//
// Deployed with verify_jwt = false because Meta calls this endpoint directly.
// Security is Meta's own webhook model instead:
//   GET  → hub.verify_token handshake (token generated by set_wa_connection)
//   POST → X-Hub-Signature-256 HMAC (app secret) verified on the RAW body;
//          unsigned or mis-signed requests are rejected 401.
//
// Handles: messages (inbound), statuses (outbound delivery/read), message
// echoes (outbound content), and history (coexistence onboarding — up to
// ~6 months of prior chats, stored with from_history = true).
// Unknown phone_number_ids auto-register in wa_numbers with brand = null so
// they appear as "unmapped" in the Setup UI.

import { createClient } from "npm:@supabase/supabase-js@2";

interface WaSecrets {
  verify_token: string | null;
  app_secret: string | null;
  access_token: string | null;
}

function supa() {
  return createClient(
    Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
  );
}

async function getSecrets(): Promise<WaSecrets> {
  const { data } = await supa().rpc("get_wa_secrets");
  return (data?.[0] as WaSecrets) ?? { verify_token: null, app_secret: null, access_token: null };
}

async function validSignature(rawBody: string, header: string | null, appSecret: string): Promise<boolean> {
  if (!header?.startsWith("sha256=")) return false;
  const key = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(appSecret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"],
  );
  const mac = await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(rawBody));
  const expected = "sha256=" + Array.from(new Uint8Array(mac)).map((b) => b.toString(16).padStart(2, "0")).join("");
  // Constant-time-ish comparison.
  if (expected.length !== header.length) return false;
  let diff = 0;
  for (let i = 0; i < expected.length; i++) diff |= expected.charCodeAt(i) ^ header.charCodeAt(i);
  return diff === 0;
}

interface WaValue {
  metadata?: { phone_number_id?: string; display_phone_number?: string };
  contacts?: { wa_id?: string; profile?: { name?: string } }[];
  messages?: {
    id: string;
    from?: string;
    to?: string;
    timestamp?: string;
    type?: string;
    text?: { body?: string };
    button?: { text?: string };
    interactive?: unknown;
  }[];
  statuses?: { id: string; status?: string; recipient_id?: string; timestamp?: string }[];
  message_echoes?: WaValue["messages"];
  history?: { metadata?: unknown; threads?: { id?: string; messages?: WaValue["messages"] }[] }[];
}

async function ensureNumber(workspaceId: number, phoneNumberId: string, display?: string): Promise<number> {
  const supabase = supa();
  const { data: existing } = await supabase
    .from("wa_numbers")
    .select("id")
    .eq("phone_number_id", phoneNumberId)
    .maybeSingle();
  if (existing) return existing.id as number;
  const { data: created } = await supabase
    .from("wa_numbers")
    .insert({ workspace_id: workspaceId, phone_number_id: phoneNumberId, display_number: display ?? null })
    .select("id")
    .single();
  return created!.id as number;
}

async function ensureConversation(
  workspaceId: number,
  numberId: number,
  contact: string,
  contactName: string | null,
): Promise<number> {
  const supabase = supa();
  const { data: existing } = await supabase
    .from("wa_conversations")
    .select("id, contact_name")
    .eq("number_id", numberId)
    .eq("wa_contact", contact)
    .maybeSingle();
  if (existing) {
    if (contactName && !existing.contact_name) {
      await supabase.from("wa_conversations").update({ contact_name: contactName }).eq("id", existing.id);
    }
    return existing.id as number;
  }
  const { data: created } = await supabase
    .from("wa_conversations")
    .insert({ workspace_id: workspaceId, number_id: numberId, wa_contact: contact, contact_name: contactName })
    .select("id")
    .single();
  return created!.id as number;
}

function messageBody(m: NonNullable<WaValue["messages"]>[number]): string | null {
  if (m.text?.body) return m.text.body;
  if (m.button?.text) return m.button.text;
  if (m.type && m.type !== "text") return `[${m.type}]`;
  return null;
}

async function ingestValue(workspaceId: number, value: WaValue, fromHistory = false): Promise<number> {
  const supabase = supa();
  const phoneNumberId = value.metadata?.phone_number_id;
  if (!phoneNumberId) return 0;
  const numberId = await ensureNumber(workspaceId, phoneNumberId, value.metadata?.display_phone_number);
  const contactName = value.contacts?.[0]?.profile?.name ?? null;
  let ingested = 0;

  const allMessages: { m: NonNullable<WaValue["messages"]>[number]; direction: "in" | "out" }[] = [
    ...(value.messages ?? []).map((m) => ({ m, direction: "in" as const })),
    ...(value.message_echoes ?? []).map((m) => ({ m, direction: "out" as const })),
  ];
  for (const thread of value.history?.flatMap((h) => h.threads ?? []) ?? []) {
    for (const m of thread.messages ?? []) {
      // History messages: direction inferred — `from` equals the business
      // number's id/display for outbound.
      const direction = m.from && value.metadata?.display_phone_number?.includes(m.from) ? "out" : "in";
      allMessages.push({ m, direction });
    }
  }

  for (const { m, direction } of allMessages) {
    const contact = direction === "in" ? (m.from ?? "unknown") : (m.to ?? value.contacts?.[0]?.wa_id ?? "unknown");
    const conversationId = await ensureConversation(workspaceId, numberId, contact, contactName);
    const sentAt = m.timestamp ? new Date(Number(m.timestamp) * 1000).toISOString() : new Date().toISOString();
    const { error } = await supabase.from("wa_messages").upsert(
      {
        workspace_id: workspaceId,
        conversation_id: conversationId,
        wa_message_id: m.id,
        direction,
        message_type: m.type ?? "text",
        body: messageBody(m),
        status: direction === "in" ? "received" : "sent",
        sent_at: sentAt,
        from_history: fromHistory,
        raw: m,
      },
      { onConflict: "wa_message_id", ignoreDuplicates: true },
    );
    if (!error) {
      ingested += 1;
      await supabase
        .from("wa_conversations")
        .update({
          last_message_at: sentAt,
          last_direction: direction,
          ...(direction === "in" && !fromHistory ? {} : {}),
        })
        .eq("id", conversationId)
        .lt("last_message_at", sentAt);
    }
  }

  for (const st of value.statuses ?? []) {
    if (!st.id || !st.status) continue;
    const mapped = ["sent", "delivered", "read", "failed"].includes(st.status) ? st.status : null;
    if (mapped) {
      await supabase.from("wa_messages").update({ status: mapped }).eq("wa_message_id", st.id);
    }
  }

  return ingested;
}

Deno.serve(async (req: Request) => {
  const url = new URL(req.url);

  if (req.method === "GET") {
    const secrets = await getSecrets();
    const mode = url.searchParams.get("hub.mode");
    const token = url.searchParams.get("hub.verify_token");
    const challenge = url.searchParams.get("hub.challenge");
    if (mode === "subscribe" && secrets.verify_token && token === secrets.verify_token && challenge) {
      return new Response(challenge, { status: 200 });
    }
    return new Response("verification failed", { status: 403 });
  }

  if (req.method !== "POST") {
    return new Response("method not allowed", { status: 405 });
  }

  const secrets = await getSecrets();
  if (!secrets.app_secret) {
    return new Response("not configured", { status: 503 });
  }
  const rawBody = await req.text();
  const signed = await validSignature(rawBody, req.headers.get("x-hub-signature-256"), secrets.app_secret);
  if (!signed) {
    return new Response("invalid signature", { status: 401 });
  }

  let payload: { entry?: { changes?: { field?: string; value?: WaValue }[] }[] };
  try {
    payload = JSON.parse(rawBody);
  } catch {
    return new Response("bad payload", { status: 400 });
  }

  const supabase = supa();
  const { data: conn } = await supabase
    .from("integration_connections")
    .select("id, workspace_id")
    .eq("provider", "WhatsApp")
    .maybeSingle();
  if (!conn) return new Response("no connection row", { status: 500 });

  let total = 0;
  for (const entry of payload.entry ?? []) {
    for (const change of entry.changes ?? []) {
      if (!change.value) continue;
      total += await ingestValue(conn.workspace_id, change.value, change.field === "history");
    }
  }

  await supabase
    .from("integration_connections")
    .update({ status: "healthy", last_success_at: new Date().toISOString() })
    .eq("id", conn.id);

  // Meta expects a fast 200 regardless of ingest count.
  return new Response(JSON.stringify({ received: true, ingested: total }), {
    status: 200,
    headers: { "Content-Type": "application/json" },
  });
});
